name: CI Client builder
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
    - uses: actions/checkout@v4
    - name: "Update System and install dependencies"
      run: |
            # update system and install dependencies
            sudo apt update
            sudo apt install -y cmake git build-essential autoconf libtool pkg-config libjsoncpp-dev libpqxx-dev libboost-all-dev
    - name: "Compile gRPC"
      run: |
            # Compile gRPC 
            export MY_INSTALL_DIR=$HOME/.local
            mkdir -p $MY_INSTALL_DIR
            export PATH="$MY_INSTALL_DIR/bin:$PATH"
            git clone --recurse-submodules -b v1.68.2 --depth 1 --shallow-submodules https://github.com/grpc/grpc
            cd grpc
            mkdir -p cmake/build
            cd cmake/build
            cmake -DgRPC_INSTALL=ON \
              -DgRPC_BUILD_TESTS=OFF \
              -DCMAKE_INSTALL_PREFIX=$MY_INSTALL_DIR \
              ../..
            make -j 2
            make install
    - name: "Compile client"
      run: |
            # Compile client
            cd ../../../client
            chmod +x genCppProto.sh
            ./genCppProto.sh
            mkdir -p cmake/build
            cd cmake/build
            cmake ../..
            make -j 2
            mv client mmclient
    - name: Upload binary release file
      uses: actions/upload-artifact@v4
      with:
        name: mmclient
        path: ${{ github.workspace }}/mmclient
